//caminho padrão para imagens

:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

= Resumo da Sintaxe da Linguagem

- link:codigos/Exemplo1.java[Declaração de variáveis]
- link:codigos/Exemplo2.java[Comandos de leitura e saída]
- link:codigos/Exemplo3.java[Desvios condicionais simples]
- link:codigos/Exemplo4.java[Desvios condicionais compostos]
- link:codigos/Exemplo5.java[Laços de repetição]

= Classe x Objeto

A classe pode ser visto como um  modelo. É nela que vai ser definido o tipo, as variáveis (atributos) e os métodos (funcionalidades) de um objeto. Na classe ocorre a projeção, porém não possível interagir com a classe. Já o objeto é uma representação da classe na memória, ou seja, através do objeto é possível armazenar dados e manipulá-los. 

Imagine o seguinte exemplo: em um caderno tem uma receita de bolo com os passos, as medidas, a forma de assar e etc. Mas através da receita é possível cortar o bolo? Depois de preparado, a partir do conteúdo que está definido na receita, o bolo existe. Dessa forma é possível cortar um pedaço do bolo, colocar ou retirar a cereja.

Segundo Sierra e Bates (2006),

"Classe: Um modelo que descreve os tipos de estado e comportamento que os objetos do seu tipo podem ter." 

"Objeto: [...] Esse objeto terá seu próprio estado e terá acesso a todos os comportamentos definidos pela sua classe."

"Estado (variáveis de instâncias): [...] os valores atribuídos às variáveis de instâncias de instâncias de um objeto compõem o estado do objeto." 

"Comportamento (métodos): [...] é nos métodos que a lógica da classe é armazenada [...] É neles que os algoritmos são executados e que os dados são manipulados."

- Referência dos textos entre aspas: SIERRA, S.; BATES, B. Certificação  Sun para Programador Java 6 Guia de Estudo. Rio de Janeiro: Alta Books, 2006.

Exemplos práticos (modelos)

- link:codigos/modelo_lampada.txt[modelo Lâmpada]
- link:codigos/modelo_calculadora.txt[modelo Calculadora]

= Resumo da Sintaxe da Linguagem (continuação)

- link:codigos/Exemplo6.java[Vetores]
- link:codigos/Exemplo7.java[Matrizes]







